### Criar cliente
POST http://localhost:8080/clientes
Content-Type: application/json

{
  "nome": "João da Silva",
  "cpf": "39053344705",
  "email": "joao@email.com",
  "telefone": "11999999999",
  "dataNascimento": "1990-01-01",
  "endereco": {
    "rua": "Rua das Flores",
    "numero": "123",
    "cep": "12345-678",
    "cidade": "São Paulo",
    "estado": "SP",
    "complemento": "Apto 101"
  }
}


### Buscar cliente por ID
GET http://localhost:8080/clientes/a5db46c6-9296-48fd-bf6f-5b0440a5f683
Accept: application/json
